refresh_products:

add_product:
  fields:
    product_id:
      example: "sensor.shopping_list_with_grocy_<your product>"
      required: true
      selector:
        text:
    quantity:
      example: 1
      required: false
      default: 1
      selector:
        number:
          min: 1
          mode: box
    note:
      example: "This is the note of the shopping list item..."
      required: false
      selector:
        text:
    disable_notification:
      example: true
      required: false
      default: false
      selector:
        boolean:

remove_product:
  fields:
    product_id:
      example: "sensor.shopping_list_with_grocy_<your product>"
      required: true
      selector:
        text:

update_note:
  fields:
    product_id:
      example: "sensor.shopping_list_with_grocy_<your product>"
      required: true
      selector:
        text:
    note:
      example: "This is the note of the shopping list item..."
      required: true
      selector:
        text:

suggest_grocery_list:
  name: Suggest Grocery List
  description: >
    Analyze product usage frequency and automatically fill the shopping list with items likely to be needed soon.
  fields:
    disable_notification:
      example: true
      required: false
      default: false
      selector:
        boolean:

reset_suggestions:
  name: Reset Shopping Suggestions
  description: >
    Clear current shopping suggestions and reset the sensor to show "Analysis in progress..." state.